name: Dynamic Amplify Deploy and Test

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy-to-amplify:
    name: Deploy PR to Amplify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        APP_ID: ${{ secrets.AMPLIFY_APP_ID }}  # Usa el secret directamente aquí
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION

    - name: Ensure Branch Exists in Amplify
      run: |
        BRANCH_NAME="branch-${{ github.event.pull_request.head.ref }}"
        aws amplify create-branch --app-id $APP_ID --branch-name $BRANCH_NAME || echo "Branch already exists"
    
    # Amplify debería manejar automáticamente los despliegues cuando detecte cambios
    - name: Trigger Amplify Deploy (auto-triggered by PR)
      run: |
        echo "Enviando un trigger para que Amplify haga el despliegue automáticamente."
        # Aquí no es necesario crear un despliegue manual si la rama ya está configurada