name: Modernize UI - Send Pushed Branch's Name To E2E Repo

on:
  push:
    branches:
      - 'CD-TEST-*'

jobs:
  send-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Send branch name to E2E repository
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            https://api.github.com/repos/ClaudioRdo/test/dispatches \
            -d '{"event_type": "deploy-and-run-test-suite", "client_payload": {"branch": "'"${BRANCH_NAME}"'"}}'