name: Dynamic Amplify Deploy and Test

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy-to-amplify:
    name: Deploy PR to Amplify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION
        echo "APP_ID=d3rzqs8zfsg1v1" >> $GITHUB_ENV  # Exporta APP_ID a todos los pasos siguientes

    - name: Verify APP_ID environment variable
      run: echo "APP_ID=$APP_ID"  # Debería funcionar ahora, ya que APP_ID está exportado en GITHUB_ENV

    - name: Ensure Branch Exists in Amplify
      run: |
        BRANCH_NAME="pr-${{ github.event.number }}"
        aws amplify create-branch --app-id $APP_ID --branch-name $BRANCH_NAME || echo "Branch already exists"

    - name: Create Amplify Deployment
      id: create-deployment
      run: |
        BRANCH_NAME="pr-${{ github.event.number }}"
        DEPLOYMENT_RESPONSE=$(aws amplify create-deployment --app-id $APP_ID --branch-name $BRANCH_NAME)
        echo "AMPLIFY_URL=$(echo $DEPLOYMENT_RESPONSE | jq -r '.jobSummary | .[0] | .summary')" >> $GITHUB_ENV

    - name: Start Amplify Deployment
      run: |
        BRANCH_NAME="pr-${{ github.event.number }}"
        DEPLOYMENT_ID=$(echo $DEPLOYMENT_RESPONSE | jq -r '.deploymentId')
        aws amplify start-deployment --app-id $APP_ID --branch-name $BRANCH_NAME --deployment-id $DEPLOYMENT_ID