name: Deploy PR to Amplify and Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy-to-amplify:
    name: Deploy PR to Amplify
    runs-on: ubuntu-latest

    env:
      APP_ID: ${{ secrets.AMPLIFY_APP_ID }} # ID de la aplicación Amplify como variable de entorno
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION

    - name: Create Amplify Deployment
      id: create-deployment
      run: |
        BRANCH_NAME="pr-${{ github.event.number }}" # Usa el número del PR como nombre del branch
        DEPLOYMENT_RESPONSE=$(aws amplify create-deployment --app-id $APP_ID --branch-name $BRANCH_NAME)
        echo "AMPLIFY_URL=$(echo $DEPLOYMENT_RESPONSE | jq -r '.jobSummary | .[0] | .summary')" >> $GITHUB_ENV

    - name: Start Amplify Deployment
      run: |
        BRANCH_NAME="pr-${{ github.event.number }}"
        DEPLOYMENT_ID=$(echo $DEPLOYMENT_RESPONSE | jq -r '.deploymentId')
        aws amplify start-deployment --app-id $APP_ID --branch-name $BRANCH_NAME --deployment-id $DEPLOYMENT_ID

  run-tests:
    name: Run Tests on Deployed PR
    runs-on: ubuntu-latest
    needs: deploy-to-amplify

    steps:
    - name: Run Test Suite
      env:
        BASE_URL: ${{ env.AMPLIFY_URL }}
      run: |
        echo "Running tests on $BASE_URL"
        npm install
        npm test -- --baseUrl=$BASE_URL