name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal
  pull_request:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/*.gradle*', '**/*.maven*') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: claudiordo
          projectKey: ClaudioRdo_my-portfolio
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
